#### Data Science  -  https://scipy.org/

**numpy**
- Used for processing N dimensional arrays

**pandas**

**matplotlib**


In [16]:
import numpy as np

li = [1,2,3]

a = np.array(li)               # creates an array

a

type(a)

b = np.arange(15)             # creates an array based on given range

b

rn = np.random.randint(0,100, size = 10)  # random implemented within the numpy 

rn

array([48, 19, 23, 68, 90, 46, 20, 23, 40, 91])

In [28]:
# 2 dimensional array

twod_array = np.random.randint(0,2, size = (3, 3))  # creating 2 dimensional array

twod_array[0][1]                                    # arrayName[0][1]

twod_array[1][2]

0

In [44]:
# 4 dimensional array

fourd_array = np.random.randint(1,10, size = (4,4,4,4))

fourd_array.ndim

fourd_array.shape

fourd_array.size

fourd_array.dtype

fourd_array.itemsize

fourd_array

array([[[[8, 6, 9, 7],
         [6, 3, 4, 1],
         [9, 5, 1, 2],
         [9, 9, 6, 5]],

        [[9, 6, 4, 3],
         [4, 5, 7, 2],
         [4, 6, 9, 7],
         [1, 7, 7, 9]],

        [[8, 4, 2, 4],
         [6, 8, 4, 2],
         [2, 3, 2, 2],
         [2, 1, 9, 8]],

        [[6, 2, 5, 2],
         [9, 3, 7, 3],
         [3, 2, 6, 5],
         [3, 9, 5, 8]]],


       [[[4, 5, 3, 2],
         [8, 3, 5, 3],
         [1, 6, 5, 4],
         [8, 2, 4, 4]],

        [[4, 2, 5, 1],
         [7, 5, 3, 8],
         [5, 7, 5, 5],
         [9, 4, 7, 3]],

        [[7, 4, 6, 6],
         [2, 1, 8, 1],
         [2, 3, 5, 8],
         [1, 6, 1, 2]],

        [[2, 2, 9, 9],
         [5, 5, 7, 9],
         [9, 8, 2, 9],
         [4, 5, 6, 1]]],


       [[[4, 5, 7, 2],
         [7, 6, 7, 3],
         [1, 9, 4, 3],
         [2, 1, 1, 7]],

        [[8, 7, 3, 5],
         [3, 2, 3, 8],
         [8, 7, 7, 2],
         [6, 1, 2, 2]],

        [[6, 4, 7, 3],
         [5, 3, 4, 4],
         [

In [53]:
# slicing in arrays in single dimension
oned = np.array(li)

oned[-1]

oned[1:]

oned[-2:]

array([2, 3])

In [71]:
# slicing in arrays in two dimensional

twod = np.array([[1,2,3,4],[5,6,7,8]])

twod[0][2:]

twod[1][-3:]

sum(twod[1])

twod.ndim

2

In [73]:
# slicing of arrays in three dimensional

threed = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

threed.ndim

threed

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [78]:
# broadcasting - while adding arrays if the on ematrix having constant values add the scalar 
## value to the other matrix it reduces time & comlexity

## dimensions must be equal or both matrices dimension should be 1 while broadcasting

import numpy as np

a = np.array([1,2,3])

b = np.array([4,4,4])

print("Addition of two matrices: ", a+4)

Addition of two matrices:  [5 6 7]


In [92]:
import numpy as np

np.ones((3,3), dtype = int )

import timeit

st = timeit.default_timer()

np.ones((4,4,4,4), dtype = int)

et = timeit.default_timer()

et - st 

7.9100000220933e-05

#### Vectorized vs Unvectorized 

#### Pandas

Use Cases

- DataCleaning

- DataProcessing

- DataAnalysis

Notations

- Series    ----> one dimensional representation of data

- DataFrames  ---> two dimensional representation of data

In [107]:
import pandas as pd

internal1 = {'s1' : 21, 's2' : 18, 's3' : 24}

#internal1 = pd.Series(internal1)

internal2 = {'s1' : 17, 's2' : 15, 's3' : 22}

#internal2 = pd.Series(internal2)

final = { 'internal1' : internal1, 'internal' : internal2 }

df = pd.DataFrame(final)  # Creating a data frame

df

internal1  internal
s1         21        17
s2         18        15
s3         24        22

In [112]:
df.columns              # gives the column names of a data frame

df.values               # gives the lists of all rows

df.values[2]            # Acessing the 3rd student marks

df.values[2][1]         # 3rd student 2nd internal marks

22

In [113]:
for row in df.values:
    print('Internal1 - ',row[0] ,', Internal2 -',row[1])

Internal1 -  21 , Internal2 - 17
Internal1 -  18 , Internal2 - 15
Internal1 -  24 , Internal2 - 22


In [131]:
df.loc['s3'] = [19, 21]    # Modifying data

#df = df.drop(3)           # removing data

df.values[2] = [21, 19]    # Modifying data based on index


internal1  internal
s1         21        17
s2         18        15
s3         21        19

In [132]:
# Reading CSV file data

import pandas as pd

filePath = 'DataFiles/Income.csv'

incomedf = pd.read_csv(filePath)


GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [134]:
# Extract income of all years in 2013

for row in incomedf.values:
    print(row[1], ':', row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [136]:
# Average income of arizona

sum = 0

for i in  range(2, 11):
    sum += incomedf.values[2][i]
    
sum/len(incomedf.values[2][2:])

47214.77777777778

In [137]:
# Average income of all states in 2012

sum = 0

for row in incomedf.values:
    sum += row[-2]
    
print(sum/len(incomedf.values))
    

50038.8
